### PR TITLE
need to actually return the repositories

### PR DESCRIPTION
**Pull request by jmahowald**
Took me a while to figure out why I was getting errors about no more pages and was getting no results.

### CODE REVIEW

**Comment by dmathieu** [comment]
Hum this is weird. This method has named return vars.
So the `repos` var should be returned already.

**Comment by jmahowald** [comment]
Ahh.  Ok hadn't used those before (working on my second go project). 
That being said, I think that either the change is still correct or there needs to be a documentation update.

By returning err as non nil, I'd argue it's breaking the conventions I've been seeing so far.  At the very least putting in a godoc comment and updating the README example of how to get a list of repositories would be correct.  Or just take this change and it'll be more idiomatic I believe.  Thoughts?

**Comment by dmathieu** [comment]
Oh right, err isn't nil hence the issue.

Could you remove the named return var, since with you change, all return are specifying the return values?

**Comment by jmahowald** [comment]
In that case, I'd need to explicitly do a make on the repos slice, correct?  Or do you mean to just remove the name on the error?

**Comment by dmathieu** [comment]
No, I mean replacing:

```
func (registry *Registry) Repositories() (repos []string, err error) {
```

To:

```
func (registry *Registry) Repositories() ([]string, error) {
```

**Comment by dmathieu** [comment]
Thank you.

**Comment by jmahowald** [comment]
de rien

**Pull request merged**
